device: &device cpu

loss_coef:
  clf_loss: 5.0
  reg_loss: 5.0
  trip_loss: 1.0
lr: 0.0005
milestones:
  - 5
  - 8
  - 12
gamma: 0.3

image_size: 224

# uncomment this, to use online face cropping
# however it is not recommended
# you can only use cpu device as device for face-cropping nn
#face_detector:
#  image_size: 512
#  margin: 100
#  min_face_size: 100
#  thresholds: [0.6, 0.7, 0.7]
#  factor: 0.709
#  device: *device

train_df:  # path to train csv file
val_df:  # path to validation csv file
path_root:  # prefix path to your images

batch_size: 96
num_workers_train: 3
num_workers_val: 3

default_root_dir: /notebook/workspace/lgsc  # path to save pytorch_lightning logs
max_epochs: 15
