#device: &device cpu

loss_coef:
  clf_loss: 5.0
  reg_loss: 5.0
  trip_loss: 1.0
lr: 0.0005
milestones:
  - 5
  - 8
  - 12
gamma: 0.3

image_size: 224
cue_log_every: 100  # will log cues every cue_log_every batches. If 0, than won't log

# uncomment this, to use online face cropping
# however it is not recommended
# you can only use cpu device as device for face-cropping nn
#face_detector:
#  image_size: 512
#  margin: 100
#  min_face_size: 100
#  thresholds: [0.6, 0.7, 0.7]
#  factor: 0.709
#  device: *device

train_df: null  # path to train csv file
val_df: null  # path to validation csv file
path_root: null  # prefix path to your images

batch_size: 96
num_workers_train: 3
num_workers_val: 3

default_root_dir: null  # path to save pytorch_lightning logs
max_epochs: 15

use_balance_sampler: True  # You can try overcome class disbalance using balance sampler
use_focal_loss: False  # You can try use focal loss instead of cross-entropy loss